/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./404.html",
    "./servicios/**/*.html",
    "./agencia-*/**/*.html",
    "./auditoria-seo/**/*.html",
    "./aviso-*/**/*.html",
    "./blog/**/*.html",
    "./casos-de-exito/**/*.html",
    "./community-manager*/**/*.html",
    "./consultor-*/**/*.html",
    "./consultoria-seo/**/*.html",
    "./contacto/**/*.html",
    "./desarrollo-web*/**/*.html",
    "./disenador-web*/**/*.html",
    "./diseno-*/**/*.html",
    "./email-marketing/**/*.html",
    "./experto-*/**/*.html",
    "./freelance-*/**/*.html",
    "./especialista-*/**/*.html",
    "./gestion-*/**/*.html",
    "./gestor-*/**/*.html",
    "./google-*/**/*.html",
    "./gracias/**/*.html",
    "./inbound-marketing/**/*.html",
    "./instagram-ads/**/*.html",
    "./landing-pages/**/*.html",
    "./linkbuilding/**/*.html",
    "./mantenimiento-*/**/*.html",
    "./marketing-para-*/**/*.html",
    "./nosotros/**/*.html",
    "./pages/**/*.html",
    "./politica-*/**/*.html",
    "./posicionamiento-web/**/*.html",
    "./precios-*/**/*.html",
    "./presupuesto/**/*.html",
    "./programador-*/**/*.html",
    "./publicidad-*/**/*.html",
    "./seo-*/**/*.html",
    "./tienda-online*/**/*.html",
    "./youtube-ads/**/*.html",
    "./generate_stitch.py",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#001e40",
        "primary-container": "#003366",
        "on-primary": "#ffffff",
        "on-primary-container": "#c8d6e5",
        "secondary-container": "#fd8b00",
        "on-secondary-container": "#603100",
        "secondary": "#e07a00",
        "surface": "#fdfdfd",
        "surface-container-low": "#f4f6fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8ebf0",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#43474f",
        "on-background": "#1a1c1e",
        "outline-variant": "#c4c7cf",
        "on-tertiary-container": "#43474f",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
