# Content for ALL 16 vertical/sector pages
# Each vertical has unique content tailored to the sector

VERTICAL_CONTENT = {
    "/marketing-para-restaurantes/": {
        "title": "Marketing para Restaurantes | Llena Tu Local Cada Día — Comunikoo",
        "meta_desc": "Marketing digital para restaurantes: SEO local, Google Maps, redes sociales, reseñas y campañas. Especialistas en hostelería. Llena tu restaurante.",
        "h1": "Marketing para Restaurantes — Estrategias Digitales para Llenar Tu Local",
        "h1_short": "Marketing Restaurantes",
        "intro": "El 90% de los clientes buscan dónde comer en Google antes de salir de casa. Si tu restaurante no aparece en esos resultados, estás regalando clientes a la competencia.",
        "sector_name": "restaurantes",
        "hook_stat": "El 90% busca restaurante en Google antes de ir.",
        "services": [
            {"title": "SEO Local y Google Maps", "desc": "Posicionamos tu restaurante en las búsquedas 'restaurante cerca de mí', 'dónde comer en [zona]' y 'mejores restaurantes [ciudad]'. Optimizamos tu ficha de Google Business Profile con fotos profesionales, carta actualizada, horarios y respuesta a reseñas."},
            {"title": "Gestión de Reseñas", "desc": "Las reseñas son el factor #1 de decisión para elegir restaurante. Implementamos una estrategia para generar reseñas positivas de forma orgánica en Google, TripAdvisor y TheFork. Monitorizamos y respondemos a todas las reseñas."},
            {"title": "Redes Sociales Gastronómicas", "desc": "Instagram y TikTok son escaparates perfectos para restaurantes. Creamos contenido que da hambre: fotos profesionales de platos, vídeos de cocina en acción, stories del día a día y reels virales. Gestionamos la comunidad y respondemos a comentarios."},
            {"title": "Google Ads para Restaurantes", "desc": "Campañas locales segmentadas por zona, tipo de cocina y momento del día. Aparece cuando alguien busca 'restaurante italiano cerca' o 'cena romántica Barcelona'. Máximo retorno con presupuestos desde 300€/mes."},
            {"title": "Web con Carta Digital y Reservas", "desc": "Diseñamos webs rápidas y atractivas con carta digital actualizable, botón de reserva (integrado con TheFork, CoverManager o reservas propias), galería de fotos y mapa de ubicación. Todo optimizado para móvil."},
            {"title": "Email Marketing y Fidelización", "desc": "Campañas de email para fidelizar: menús especiales, eventos, descuentos para repetidores, felicitaciones de cumpleaños. Convierte clientes puntuales en habituales."},
        ],
        "testimonial_quote": "Desde que trabajan nuestro SEO local, hemos pasado de 3 a 5 turnos llenos entre semana. Las reservas online se han multiplicado por 4.",
        "testimonial_author": "Carlos Martín, Restaurante La Brasería, Barcelona",
        "cta_title": "¿Quieres llenar tu restaurante?",
        "cta_button": "Auditoría gratis para hostelería",
        "faqs": [
            ("¿Cuánto cuesta el marketing para un restaurante?", "Depende de tus objetivos y del nivel de competencia en tu zona. Los planes para restaurantes empiezan desde 390€/mes incluyendo SEO local y gestión de reseñas. Podemos escalar con redes sociales, Google Ads y email marketing según necesidades."),
            ("¿Qué red social es mejor para restaurantes?", "Instagram es la red principal para restaurantes: es visual, permite mostrar platos y tiene funciones de ubicación y reserva. TikTok está creciendo rápidamente para contenido gastronómico viral. Facebook sigue siendo útil para eventos y público 35+. Recomendamos empezar con Instagram + Google Business Profile."),
            ("¿Cómo consigo más reseñas en Google?", "Implementamos un sistema automatizado: después de cada visita, el cliente recibe un mensaje (WhatsApp, email o QR en mesa) con enlace directo a dejar reseña en Google. Lo importante es facilitarlo al máximo y responder siempre a las reseñas recibidas, tanto positivas como negativas."),
            ("¿Necesito página web si ya estoy en TheFork y Google Maps?", "Sí. Tu web es el único canal que controlas al 100%. TheFork cobra comisiones por reserva y Google puede cambiar sus reglas. Una web propia con reservas directas reduce comisiones y te da independencia. Además, posiciona para keywords que las plataformas no cubren."),
            ("¿Funciona Google Ads para restaurantes?", "Sí, especialmente campañas locales. Cuando alguien busca 'restaurante japonés Barcelona' y tu anuncio aparece primero, la tasa de conversión es altísima porque la intención de compra es inmediata. Con presupuestos de 300-500€/mes ya se ven resultados claros."),
            ("¿Gestionáis presencia en Uber Eats y Glovo?", "Sí, optimizamos tus perfiles en plataformas de delivery: fotos profesionales, descripciones optimizadas, gestión de precios y promociones. También trabajamos estrategia para reducir la dependencia de estas plataformas y potenciar el canal propio."),
        ],
    },

    "/marketing-para-hoteles/": {
        "title": "Marketing para Hoteles | Más Reservas Directas — Comunikoo",
        "meta_desc": "Marketing digital para hoteles: más reservas directas, menos comisiones OTAs. SEO hotelero, Google Hotel Ads, redes sociales y web con motor de reservas.",
        "h1": "Marketing para Hoteles — Más Reservas Directas, Menos Dependencia de OTAs",
        "h1_short": "Marketing Hoteles",
        "intro": "Las OTAs como Booking y Expedia se llevan entre el 15% y 25% de comisión por cada reserva. Una estrategia de marketing digital bien ejecutada puede reducir esa dependencia y multiplicar tus reservas directas.",
        "sector_name": "hoteles",
        "hook_stat": "Reduce comisiones del 15-25% de OTAs con reservas directas.",
        "services": [
            {"title": "Web con Motor de Reservas", "desc": "Diseñamos webs hoteleras con motor de reservas integrado, galería profesional, virtual tour y paridad de precios. Optimizadas para convertir el tráfico en reservas directas sin comisiones."},
            {"title": "SEO Hotelero", "desc": "Posicionamos tu hotel para búsquedas como 'hotel en [destino]', 'hotel con piscina [ciudad]', 'hotel boutique [zona]'. Estrategia de contenido basada en destino, experiencias y temporadas."},
            {"title": "Google Hotel Ads y Metabuscadores", "desc": "Gestionamos campañas en Google Hotel Ads, Trivago, Kayak y TripAdvisor. Tu hotel aparece con precio directo cuando el viajero compara opciones. CPA más bajo que OTAs."},
            {"title": "Redes Sociales y Reputación", "desc": "Contenido aspiracional en Instagram que inspira viajes. Gestión de reputación en TripAdvisor, Google y Booking. Respuesta profesional a reseñas que construye confianza."},
            {"title": "Email Marketing Hotelero", "desc": "Campañas pre-stay (upselling de servicios), post-stay (solicitud de reseña), newsletter estacional y programa de fidelización para generar repetición de reservas."},
        ],
        "testimonial_quote": "En 8 meses, nuestras reservas directas pasaron del 18% al 42% del total. La reducción en comisiones OTA ha sido de más de 35.000€ al año.",
        "testimonial_author": "Directora de Marketing, Hotel Boutique, Barcelona",
        "cta_title": "¿Quieres más reservas directas?",
        "cta_button": "Auditoría hotelera gratis",
        "faqs": [
            ("¿Cómo aumento las reservas directas de mi hotel?", "Con una combinación de web optimizada con motor de reservas, SEO para captar tráfico orgánico, Google Hotel Ads para aparecer en metabuscadores con precio directo, y email marketing para fidelizar huéspedes anteriores. El objetivo es que el cliente te encuentre directamente, no a través de Booking."),
            ("¿Merece la pena competir con Booking?", "No se trata de competir directamente sino de reducir la dependencia. Booking seguirá siendo un canal importante, pero cada reserva directa que consigues te ahorra un 15-25% de comisión. Un hotel que pase del 20% al 40% de reservas directas puede ahorrar decenas de miles de euros al año."),
            ("¿Qué es Google Hotel Ads?", "Es la plataforma de Google que muestra precios de hotel directamente en los resultados de búsqueda y en Google Maps. Cuando un usuario busca tu hotel, ve los precios de Booking, Expedia y también tu precio directo. Pagas por clic o por reserva, con CPAs mucho más bajos que las comisiones de OTAs."),
            ("¿Cuánto cuesta el marketing hotelero?", "Los planes para hoteles empiezan desde 990€/mes para hoteles pequeños (SEO + web + Google Hotel Ads básico) y desde 2.500€/mes para hoteles medianos-grandes con estrategia multicanal completa. El retorno se mide en reducción de comisiones OTA y aumento de revenue directo."),
            ("¿Funciona para hoteles pequeños?", "Absolutamente. Los hoteles boutique y pequeños son los que más se benefician porque cada reserva directa tiene un impacto proporcionalmente mayor en su margen. Además, el contenido y la experiencia personalizada son ventajas competitivas frente a grandes cadenas."),
        ],
    },

    "/marketing-para-clinicas-dentales/": {
        "title": "Marketing para Clínicas Dentales | Más Pacientes — Comunikoo",
        "meta_desc": "Marketing digital para clínicas dentales: SEO, Google Ads, redes sociales y web. Especialistas en captar pacientes de odontología. +300% en leads.",
        "h1": "Marketing para Clínicas Dentales — Captamos Pacientes que Llenan Tu Agenda",
        "h1_short": "Marketing Dental",
        "intro": "El 80% de los pacientes nuevos buscan dentista en internet antes de pedir cita. Las reseñas online son el factor #1 de decisión. Tu clínica dental necesita una estrategia digital profesional para captar pacientes de forma constante.",
        "sector_name": "clínicas dentales",
        "hook_stat": "El 80% de pacientes nuevos busca dentista online.",
        "services": [
            {"title": "SEO Local para Dentistas", "desc": "Posicionamos tu clínica en las búsquedas 'dentista cerca de mí', 'clínica dental [barrio]', 'ortodoncista [ciudad]'. Optimizamos tu ficha de Google con fotos del equipo, servicios y reseñas para aparecer en el pack local."},
            {"title": "Google Ads por Tratamiento", "desc": "Campañas específicas para cada tratamiento: implantes dentales, ortodoncia invisible, blanqueamiento, carillas. El paciente busca un tratamiento concreto y encuentra tu clínica. Leads cualificados con coste controlado."},
            {"title": "Web de Clínica Dental", "desc": "Diseño web profesional que transmite confianza: equipo médico con fotos reales, tratamientos explicados en lenguaje accesible, testimonios de pacientes, sistema de cita online y cumplimiento RGPD sanitario."},
            {"title": "Redes Sociales Dentales", "desc": "Contenido educativo y de confianza: antes/después de tratamientos (con consentimiento), consejos de salud dental, presentación del equipo, tecnología de la clínica. Instagram y TikTok son ideales para mostrar resultados visualmente."},
            {"title": "Gestión de Reseñas", "desc": "Las reseñas son decisivas en salud. Sistema automatizado de solicitud de reseñas post-tratamiento, monitorización de Google y Doctoralia, y respuesta profesional a todas las reseñas."},
            {"title": "Email Marketing Dental", "desc": "Recordatorios de revisiones periódicas, información sobre nuevos tratamientos, promociones estacionales (blanqueamiento en verano, revisiones en septiembre). Fideliza pacientes y genera revisitas."},
        ],
        "testimonial_quote": "En 5 meses, nuestros leads mensuales pasaron de 12 a 47. La inversión en marketing se ha amortizado con creces solo con los implantes captados por Google Ads.",
        "testimonial_author": "Dr. Alejandro Ruiz, Clínica Dental Ruiz, Madrid",
        "cta_title": "¿Quieres más pacientes en tu clínica?",
        "cta_button": "Auditoría gratis para clínicas dentales",
        "faqs": [
            ("¿Cuánto cuesta el marketing para una clínica dental?", "Los planes para clínicas dentales empiezan desde 590€/mes (SEO local + gestión de reseñas) y desde 990€/mes con Google Ads incluido. El retorno medio es de 5-8x: por cada euro invertido, se generan entre 5 y 8 euros en nuevos tratamientos."),
            ("¿Qué resultados puedo esperar?", "En los primeros 3 meses se suelen ver mejoras en posicionamiento local y primeras citas desde Google Ads. Entre el mes 4 y 6, el SEO empieza a generar tráfico orgánico constante. Nuestros clientes dentales ven un aumento medio del 300% en leads cualificados en 6 meses."),
            ("¿Gestionáis campañas para tratamientos específicos?", "Sí, creamos campañas segmentadas por tratamiento: implantes, ortodoncia invisible, blanqueamiento, periodoncia, etc. Cada tratamiento tiene sus keywords, su landing page y su seguimiento de conversiones independiente."),
            ("¿Cumplís con la normativa sanitaria de publicidad?", "Sí, todo el contenido que creamos cumple con la normativa de publicidad sanitaria en España. No hacemos promesas de resultados médicos, usamos antes/después solo con consentimiento del paciente, e identificamos siempre al centro y los profesionales."),
            ("¿Necesito una web nueva?", "No necesariamente. Podemos trabajar con tu web actual si tiene una base decente, optimizándola para SEO y conversión. Si la web tiene más de 3-4 años o no es responsive, sí recomendamos un rediseño. Te lo indicamos en la auditoría gratuita."),
        ],
    },

    "/marketing-para-clinicas-esteticas/": {
        "title": "Marketing para Clínicas Estéticas | Pacientes Premium — Comunikoo",
        "meta_desc": "Marketing digital para clínicas de medicina estética. Captamos pacientes premium con SEO, Google Ads y redes sociales. Sector en auge.",
        "h1": "Marketing para Clínicas Estéticas — Captamos Pacientes Premium para Tu Centro",
        "h1_short": "Marketing Estética",
        "intro": "La medicina estética es uno de los sectores con mayor crecimiento en España (15% anual). Los pacientes son exigentes, investigan online y comparan. Tu estrategia digital debe transmitir exclusividad, confianza y resultados.",
        "sector_name": "clínicas estéticas",
        "hook_stat": "Sector que crece un 15% anual en España.",
        "services": [
            {"title": "SEO por Tratamiento", "desc": "Posicionamos tu clínica para búsquedas específicas: 'botox [ciudad]', 'ácido hialurónico labios', 'liposucción precio', 'rejuvenecimiento facial'. Cada tratamiento tiene su propia estrategia de keywords y contenido."},
            {"title": "Google Ads Estética", "desc": "Campañas por tratamiento y zona geográfica. El paciente que busca 'relleno de labios Madrid' tiene alta intención de compra. Optimizamos para coste por lead y calidad del paciente, no solo volumen."},
            {"title": "Instagram y TikTok", "desc": "Las redes visuales son perfectas para estética: resultados de tratamientos, proceso en clínica, equipo médico, tecnología. Contenido educativo que genera confianza y posiciona como referente."},
            {"title": "Web Premium", "desc": "Diseño web que refleja exclusividad: galería de resultados, equipo médico con credenciales, sistema de cita online, chat de WhatsApp y todo optimizado para captar pacientes premium."},
        ],
        "testimonial_quote": "Nuestro coste por lead se ha reducido un 40% mientras la calidad de los pacientes ha mejorado notablemente. Ahora captamos el perfil exacto que buscamos.",
        "testimonial_author": "Dra. Laura Vega, Clínica Estética Premium, Barcelona",
        "cta_title": "¿Quieres captar pacientes premium?",
        "cta_button": "Consulta gratis para estética",
        "faqs": [
            ("¿Se puede publicitar tratamientos estéticos en Google?", "Sí, con ciertas restricciones. Google permite publicitar tratamientos de medicina estética siempre que se cumplan sus políticas sanitarias. No se pueden hacer promesas de resultados garantizados ni usar antes/después en los anuncios directamente. Nosotros conocemos las normas y creamos campañas que las cumplen."),
            ("¿Qué redes sociales funcionan para estética?", "Instagram es la red principal: permite mostrar resultados, contar historias de pacientes y construir marca personal del médico. TikTok está creciendo mucho para contenido educativo sobre tratamientos. YouTube funciona para vídeos explicativos más largos. Recomendamos empezar con Instagram + Google."),
            ("¿Cuánto cuesta el marketing para clínicas estéticas?", "Los planes empiezan desde 790€/mes. El sector estético tiene tickets medios altos (500-5.000€ por tratamiento), lo que hace que el retorno de inversión en marketing sea muy rentable. Un solo paciente nuevo de implantes capilares puede cubrir varios meses de inversión en marketing."),
        ],
    },

    "/marketing-para-psicologos/": {
        "title": "Marketing para Psicólogos | Más Pacientes Online — Comunikoo",
        "meta_desc": "Marketing digital para psicólogos: web profesional, SEO, Google Ads y directorios. Captación ética respetando la sensibilidad de la salud mental.",
        "h1": "Marketing para Psicólogos — Conecta con Quienes Necesitan Tu Ayuda",
        "h1_short": "Marketing Psicólogos",
        "intro": "La demanda de servicios psicológicos se ha triplicado en los últimos años. Los pacientes buscan psicólogo en Google, comparan perfiles en Doctoralia y leen reseñas antes de pedir cita. Una presencia digital profesional y ética es imprescindible.",
        "sector_name": "psicólogos",
        "hook_stat": "La demanda de psicología se ha triplicado.",
        "services": [
            {"title": "Web Profesional de Confianza", "desc": "Diseño web que transmite empatía y profesionalidad: tu perfil y formación, especialidades, enfoque terapéutico, sistema de cita online y blog con contenido psicoeducativo. Todo con un tono cálido y accesible."},
            {"title": "SEO por Especialidad y Zona", "desc": "Posicionamos tu consulta para búsquedas como 'psicólogo ansiedad [ciudad]', 'terapia de pareja [barrio]', 'psicóloga infantil [zona]'. SEO local + contenido de autoridad por especialidad."},
            {"title": "Google Ads Sensible", "desc": "Campañas cuidadosas y éticas. Cuando alguien busca ayuda psicológica, tu anuncio aparece con un mensaje empático y profesional. Segmentación por especialidad, zona y momento del día."},
            {"title": "Presencia en Directorios", "desc": "Optimización de perfiles en Doctoralia, Mundopsicólogos, Psicólogo Online y Google Business Profile. Fotos profesionales, descripción de servicios y gestión de valoraciones."},
        ],
        "testimonial_quote": "Antes dependía al 100% de Doctoralia. Ahora el 60% de mis pacientes nuevos vienen de mi web y Google directamente. Mi agenda está llena de lunes a viernes.",
        "testimonial_author": "Psicóloga Clínica, Consulta Privada, Madrid",
        "cta_title": "¿Quieres más pacientes en tu consulta?",
        "cta_button": "Consulta gratis para psicólogos",
        "faqs": [
            ("¿Se puede hacer publicidad de servicios psicológicos?", "Sí, siempre que se respete el código deontológico del COP (Colegio Oficial de Psicólogos). La comunicación debe ser veraz, no crear expectativas infundadas y respetar la dignidad del paciente. Nosotros conocemos estas normas y creamos campañas que las cumplen escrupulosamente."),
            ("¿Cuánto cuesta el marketing para un psicólogo?", "Los planes para psicólogos y consultas individuales empiezan desde 350€/mes (SEO local + directorios) y desde 590€/mes con Google Ads incluido. Teniendo en cuenta que una sesión cuesta 60-100€, con 2-3 pacientes nuevos al mes la inversión se amortiza."),
            ("¿Mejor web propia o solo Doctoralia?", "Ambas, pero la web propia es fundamental. Doctoralia es un buen escaparate, pero cobran comisiones crecientes y tú no controlas la plataforma. Tu web es tuya: posiciona en Google, transmite tu enfoque terapéutico y captas pacientes sin intermediarios."),
            ("¿Funciona Google Ads para psicólogos?", "Sí, muy bien. Cuando alguien busca 'psicólogo ansiedad Barcelona', tiene una necesidad real e inmediata. Google Ads te pone ahí en ese momento. Los costes por clic en psicología son moderados (2-5€) y la tasa de conversión a cita suele ser alta."),
        ],
    },

    "/marketing-para-veterinarias/": {
        "title": "Marketing para Veterinarias | Más Clientes — Comunikoo",
        "meta_desc": "Marketing digital para clínicas veterinarias: SEO local, Google Maps, redes sociales y web. Captamos dueños de mascotas en tu zona.",
        "h1": "Marketing para Veterinarias — Atrae Más Dueños de Mascotas a Tu Clínica",
        "h1_short": "Marketing Veterinarias",
        "intro": "España tiene más de 28 millones de mascotas y el sector veterinario crece un 8% anual. Los dueños buscan veterinario en Google Maps, leen reseñas y valoran la cercanía. Tu clínica necesita ser visible online donde sus clientes buscan.",
        "sector_name": "veterinarias",
        "hook_stat": "28M de mascotas en España. El sector crece un 8% anual.",
        "services": [
            {"title": "SEO Local y Google Maps", "desc": "Posiciona tu veterinaria en 'veterinario cerca de mí', 'urgencias veterinarias [zona]' y 'clínica veterinaria [barrio]'. Optimización de Google Business Profile con servicios, horarios y fotos."},
            {"title": "Redes Sociales", "desc": "Contenido emocional que conecta: mascotas recuperadas, consejos de salud animal, presentación del equipo, vídeos educativos. Instagram y TikTok son ideales para crear comunidad y confianza."},
            {"title": "Web con Cita Online", "desc": "Web profesional con servicios, equipo veterinario, urgencias, cita online y blog de salud animal. Todo optimizado para móvil porque el dueño busca veterinario desde el teléfono."},
            {"title": "Email y SMS Marketing", "desc": "Recordatorios automáticos de vacunas, desparasitaciones y revisiones. Campañas estacionales (leishmaniosis en verano, procesionaria en primavera). Fidelización que genera revisitas."},
        ],
        "testimonial_quote": "Las citas online se han triplicado y las urgencias nos encuentran directamente en Google Maps. El marketing ha sido la mejor inversión que hemos hecho.",
        "testimonial_author": "Veterinaria Responsable, Clínica Veterinaria, Barcelona",
        "cta_title": "¿Quieres más clientes en tu veterinaria?",
        "cta_button": "Consulta gratis para veterinarias",
        "faqs": [
            ("¿Cuánto cuesta el marketing para veterinarias?", "Los planes empiezan desde 390€/mes para SEO local y Google Business Profile. Con redes sociales y Google Ads, desde 690€/mes. El retorno es rápido porque el ticket medio veterinario (consultas + tratamientos) permite amortizar la inversión en pocas semanas."),
            ("¿Qué redes sociales funcionan para veterinarios?", "Instagram es la mejor red para veterinarias: los contenidos de mascotas generan mucho engagement natural. TikTok está creciendo para contenido educativo animal. Facebook sigue útil para comunicar horarios, urgencias y servicios a un público local más adulto."),
            ("¿Funciona Google Ads para urgencias veterinarias?", "Sí, especialmente. Cuando un dueño busca 'urgencias veterinarias abierto ahora', la intención es inmediata. Las campañas de urgencias tienen las tasas de conversión más altas del sector veterinario. Recomendamos campañas específicas para urgencias 24h."),
        ],
    },

    "/marketing-para-abogados/": {
        "title": "Marketing para Abogados | Clientes para Tu Despacho — Comunikoo",
        "meta_desc": "Marketing digital para despachos de abogados: SEO, Google Ads, web profesional y contenido legal. Captamos clientes cualificados para tu bufete.",
        "h1": "Marketing para Abogados — Más Clientes Cualificados para Tu Despacho",
        "h1_short": "Marketing Abogados",
        "intro": "El 96% de las personas que necesitan un abogado buscan en Google primero. El boca a boca sigue siendo importante, pero ya no es suficiente. Tu despacho necesita visibilidad online para captar clientes de forma constante.",
        "sector_name": "abogados",
        "hook_stat": "El 96% busca abogado en Google antes de llamar.",
        "services": [
            {"title": "SEO por Especialidad Legal", "desc": "Posicionamos tu despacho para búsquedas por especialidad: 'abogado divorcio [ciudad]', 'abogado laboralista [zona]', 'abogado herencias [ciudad]'. Cada área de práctica tiene su propia estrategia de contenido y keywords."},
            {"title": "Google Ads para Abogados", "desc": "Campañas por especialidad y urgencia. Cuando alguien busca 'abogado despido improcedente' o 'abogado accidente de tráfico', tu anuncio aparece primero. Leads de alta intención con presupuesto controlado."},
            {"title": "Web de Despacho Profesional", "desc": "Diseño web que transmite autoridad y confianza: equipo de abogados con formación y experiencia, áreas de práctica explicadas, artículos de referencia, testimonios y sistema de consulta online. Cumplimiento RGPD."},
            {"title": "Contenido Legal de Autoridad", "desc": "Blog con artículos de actualidad jurídica, guías prácticas y FAQ legales que posicionan tu despacho como referente. El contenido legal de calidad genera tráfico orgánico constante y demuestra expertise ante Google (E-E-A-T)."},
            {"title": "SEO Local para Despachos", "desc": "Posicionamiento en Google Maps para búsquedas locales. Optimización de Google Business Profile con categorías legales, fotos del despacho y gestión de reseñas profesionales."},
        ],
        "testimonial_quote": "Pasamos de depender del boca a boca a recibir 25 consultas cualificadas al mes por nuestra web. El SEO ha transformado nuestro despacho.",
        "testimonial_author": "Socio Director, Despacho de Abogados, Madrid",
        "cta_title": "¿Quieres más clientes para tu despacho?",
        "cta_button": "Consulta gratis para abogados",
        "faqs": [
            ("¿Es ético que un abogado haga marketing?", "Absolutamente. El marketing para abogados es legal y ético siempre que cumpla con el Código Deontológico de la Abogacía Española. La publicidad debe ser veraz, no puede crear expectativas infundadas y debe identificar al profesional. Nosotros conocemos estas normas y las respetamos escrupulosamente."),
            ("¿Cuánto cuesta el marketing para un despacho?", "Los planes para despachos empiezan desde 590€/mes (SEO + web básica) y desde 990€/mes con Google Ads incluido. Teniendo en cuenta que un caso nuevo puede valer 1.000-10.000€ en honorarios, la inversión se recupera con 1-2 clientes al mes."),
            ("¿Google Ads funciona para abogados?", "Muy bien. El sector legal tiene CPCs más altos (5-15€ por clic) pero también tickets altos. Un lead de 'abogado herencias Madrid' que se convierte en cliente puede generar 3.000-5.000€ en honorarios. El ROI en Google Ads para abogados suele ser de 5-10x."),
            ("¿Qué especialidades legales funcionan mejor online?", "Las que tienen mayor demanda de búsqueda en España son: derecho laboral (despidos, ERTEs), derecho de familia (divorcios, custodia), extranjería, accidentes de tráfico, derecho penal y herencias. Cada especialidad requiere su propia estrategia de contenido y keywords."),
        ],
    },

    "/marketing-para-asesorias/": {
        "title": "Marketing para Asesorías y Gestorías | Diferénciate — Comunikoo",
        "meta_desc": "Marketing digital para asesorías y gestorías: web profesional, SEO, Google Ads y contenido. Diferénciate en un mercado saturado.",
        "h1": "Marketing para Asesorías — Diferénciate y Capta Clientes en un Mercado Saturado",
        "h1_short": "Marketing Asesorías",
        "intro": "Hay más de 90.000 asesorías y gestorías en España. Casi todas ofrecen los mismos servicios. La diferencia entre llenar tu cartera de clientes o luchar por sobrevivir está en cómo te posicionas online.",
        "sector_name": "asesorías",
        "hook_stat": "+90.000 asesorías en España. ¿Cómo te diferencias?",
        "services": [
            {"title": "Web Orientada a Captación", "desc": "Web profesional con servicios claros, calculadoras interactivas (coste autónomo, simulador de nómina), formulario de contacto optimizado y blog con contenido fiscal y laboral actualizado."},
            {"title": "SEO por Servicio", "desc": "Posicionamiento para 'asesoría fiscal [ciudad]', 'gestoría laboral [zona]', 'asesor contable [barrio]'. Contenido SEO sobre novedades fiscales, obligaciones tributarias y cambios legales."},
            {"title": "Google Ads y LinkedIn", "desc": "Campañas en Google para captar autónomos y pymes que buscan gestoría. LinkedIn Ads para captación B2B de empresas que buscan externalizar su contabilidad o nóminas."},
            {"title": "Newsletter de Actualidad", "desc": "Newsletter semanal/mensual con novedades fiscales, plazos de declaraciones, cambios laborales. Posiciona tu asesoría como referente y mantiene a los clientes informados y fidelizados."},
        ],
        "testimonial_quote": "La newsletter mensual ha sido un cambio radical. Nuestros clientes nos ven como expertos de referencia y nos recomiendan constantemente.",
        "testimonial_author": "Director, Asesoría Fiscal, Barcelona",
        "cta_title": "¿Quieres diferenciar tu asesoría?",
        "cta_button": "Consulta gratis para asesorías",
        "faqs": [
            ("¿Cuánto cuesta el marketing para una asesoría?", "Los planes empiezan desde 490€/mes. Para asesorías pequeñas, empezamos con SEO local y web optimizada. Para asesorías que quieren escalar, añadimos Google Ads, LinkedIn y marketing de contenidos."),
            ("¿Funciona el marketing digital para gestorías pequeñas?", "Sí, especialmente. Las gestorías pequeñas pueden competir online sin necesidad de grandes presupuestos. El SEO local y una web bien optimizada pueden generar leads constantes desde búsquedas como 'gestoría cerca de mí' o 'asesoría fiscal [ciudad]'."),
            ("¿Qué canal funciona mejor para asesorías?", "Google (SEO + Ads) es el canal principal: el cliente que busca 'asesoría laboral' tiene una necesidad real. LinkedIn funciona muy bien para captar empresas medianas. Y el email marketing (newsletter de actualidad fiscal) es el mejor canal para fidelizar y generar recomendaciones."),
        ],
    },

    "/marketing-para-inmobiliarias/": {
        "title": "Marketing para Inmobiliarias | Leads Cualificados — Comunikoo",
        "meta_desc": "Marketing digital para inmobiliarias: SEO, Google Ads, redes sociales y portales. Captamos leads de compradores y vendedores cualificados.",
        "h1": "Marketing para Inmobiliarias — Leads Cualificados de Compradores y Vendedores",
        "h1_short": "Marketing Inmobiliarias",
        "intro": "El sector inmobiliario en España mueve más de 60.000 millones de euros anuales. El comprador investiga online una media de 3 meses antes de contactar con una inmobiliaria. Estar presente en cada fase de su búsqueda es la clave.",
        "sector_name": "inmobiliarias",
        "hook_stat": "El comprador investiga 3 meses online antes de contactar.",
        "services": [
            {"title": "Web con Buscador de Propiedades", "desc": "Web inmobiliaria profesional con buscador de inmuebles, fichas de propiedad optimizadas, filtros avanzados, galería de fotos y contacto directo. Integración con tu CRM inmobiliario."},
            {"title": "SEO Inmobiliario", "desc": "Posicionamiento por zona y tipo: 'pisos en venta [barrio]', 'casas [urbanización]', 'alquiler oficinas [zona]'. Contenido de zona (guías de barrio, precios m², infraestructuras) que atrae tráfico cualificado."},
            {"title": "Portales y Google Ads", "desc": "Optimización de perfiles en Idealista, Fotocasa y pisos.com. Campañas de Google Ads para búsquedas de alta intención inmobiliaria. Presupuesto optimizado para maximizar leads."},
            {"title": "Marketing de Captación", "desc": "Campañas específicas para captar propietarios que quieren vender: 'valoración gratuita de tu piso', 'vende tu casa en [zona]'. Landing pages de captación + Google Ads + Facebook Ads."},
            {"title": "Redes Sociales Inmobiliarias", "desc": "Tours virtuales en Instagram y TikTok, vídeos de propiedades, contenido de zona y lifestyle. Reels de propiedades que generan alcance orgánico y consultas directas."},
        ],
        "testimonial_quote": "Los leads de la web superan ya a los de los portales en calidad. Y nos cuestan la mitad. La inversión en SEO ha sido la mejor decisión para nuestro negocio.",
        "testimonial_author": "Director Comercial, Inmobiliaria, Barcelona",
        "cta_title": "¿Quieres más leads inmobiliarios?",
        "cta_button": "Consulta gratis para inmobiliarias",
        "faqs": [
            ("¿Cuánto cuesta el marketing para una inmobiliaria?", "Desde 690€/mes para planes de SEO + Google Ads básico. Planes completos con web, portales, redes sociales y campañas de captación desde 1.500€/mes. El sector inmobiliario tiene tickets altos (comisiones de 3.000-15.000€ por operación), lo que hace el marketing muy rentable."),
            ("¿Mejor invertir en portales o en web propia?", "Ambos, pero la web propia debe ser la prioridad a medio plazo. Los portales (Idealista, Fotocasa) son necesarios pero generan dependencia y los costes suben cada año. Tu web propia con SEO genera leads sin comisiones recurrentes. La estrategia ideal es: portales para corto plazo, SEO propio para medio-largo plazo."),
            ("¿Google Ads funciona para vender pisos?", "Sí, especialmente para propiedades o zonas específicas. Los anuncios de búsqueda capturan compradores con intención real ('comprar piso 3 habitaciones [zona]'). Las campañas de display son útiles para campañas de captación de propietarios. El CPC es moderado (1-4€) y un lead convertido vale miles de euros."),
        ],
    },

    "/marketing-para-empresas-de-reformas/": {
        "title": "Marketing para Empresas de Reformas | Más Presupuestos — Comunikoo",
        "meta_desc": "Marketing digital para empresas de reformas: SEO local, Google Ads y web con portfolio. Captamos clientes que piden presupuesto en tu zona.",
        "h1": "Marketing para Empresas de Reformas — Más Solicitudes de Presupuesto Cada Mes",
        "h1_short": "Marketing Reformas",
        "intro": "El cliente que necesita una reforma busca en Google, mira fotos de trabajos anteriores y compara presupuestos. Si tu empresa de reformas no tiene presencia online profesional, estás perdiendo los mejores clientes.",
        "sector_name": "empresas de reformas",
        "hook_stat": "Tu cliente busca en Google, no en las Páginas Amarillas.",
        "services": [
            {"title": "SEO Local para Reformas", "desc": "Posiciona tu empresa en 'reformas [ciudad]', 'empresa de reformas [barrio]', 'reformas cocinas [zona]', 'reformas baños [ciudad]'. El SEO local es clave porque el cliente busca reformistas cerca de su zona."},
            {"title": "Google Ads por Tipo de Reforma", "desc": "Campañas específicas: reformas integrales, cocinas, baños, locales comerciales. Cada tipo de reforma tiene sus keywords y su landing page. Leads de alta intención que buscan presupuesto ahora."},
            {"title": "Web con Portfolio de Antes/Después", "desc": "Web profesional con galería de proyectos (antes/después), servicios detallados, zona de cobertura, presupuesto online y testimonios de clientes. Las fotos de trabajos reales son tu mejor comercial."},
            {"title": "Google Business Profile y Reseñas", "desc": "Ficha optimizada con fotos de obras, servicios y zona de cobertura. Estrategia de generación de reseñas post-obra. Las reseñas son decisivas en reformas: el cliente necesita confiar antes de dar las llaves de su casa."},
        ],
        "testimonial_quote": "Antes teníamos 2-3 consultas al mes. Ahora recibimos 15-20 solicitudes de presupuesto mensuales, la mayoría de buena calidad. La web con portfolio ha sido clave.",
        "testimonial_author": "Gerente, Empresa de Reformas, Madrid",
        "cta_title": "¿Quieres más solicitudes de presupuesto?",
        "cta_button": "Consulta gratis para reformas",
        "faqs": [
            ("¿Cuánto cuesta el marketing para una empresa de reformas?", "Planes desde 490€/mes con SEO local y Google Business Profile. Con Google Ads incluido desde 790€/mes. El ticket medio de una reforma (5.000-30.000€) hace que con 1-2 clientes nuevos al mes ya sea muy rentable."),
            ("¿Funciona Google Ads para reformas?", "Excelentemente. Cuando alguien busca 'empresa reformas integrales Barcelona', tiene una necesidad real y busca presupuesto. Los CPCs son moderados (2-6€) y la tasa de conversión a solicitud de presupuesto es alta. El ROI en reformas es uno de los mejores que vemos."),
            ("¿Necesito web si ya estoy en Habitissimo?", "Habitissimo y similares son útiles pero cobran por lead y la competencia es feroz (5+ empresas compitiendo por el mismo cliente). Tu web propia con SEO genera leads exclusivos (solo te contactan a ti) y sin comisiones. Recomendamos web propia + Google Ads como canal principal."),
        ],
    },

    "/marketing-para-autoescuelas/": {
        "title": "Marketing para Autoescuelas | Más Alumnos — Comunikoo",
        "meta_desc": "Marketing digital para autoescuelas: SEO local, Google Ads, redes sociales y reseñas. Atrae alumnos que buscan autoescuela online.",
        "h1": "Marketing para Autoescuelas — Más Alumnos Matriculados con Estrategia Digital",
        "h1_short": "Marketing Autoescuelas",
        "intro": "Los jóvenes de hoy buscan autoescuela en Google, no preguntan al vecino. Comparan precios, leen reseñas y miran redes sociales. Tu autoescuela necesita estar donde tus futuros alumnos buscan.",
        "sector_name": "autoescuelas",
        "hook_stat": "Los jóvenes buscan autoescuela en Google y redes sociales.",
        "services": [
            {"title": "SEO Local", "desc": "Posicionamiento en 'autoescuela cerca de mí', 'autoescuela [barrio]', 'precio carnet de conducir [ciudad]'. SEO local para que aparezcan cuando buscan en su zona."},
            {"title": "Google Ads por Carnet", "desc": "Campañas segmentadas por tipo de carnet (B, moto, camión) y zona. 'Autoescuela precio carnet B [ciudad]' es una búsqueda de alta conversión."},
            {"title": "Redes Sociales Jóvenes", "desc": "TikTok e Instagram son donde está tu público: contenido divertido sobre el proceso de sacarse el carnet, consejos para el examen, retos, memes. Lenguaje joven y cercano."},
            {"title": "Web con Precios y Reseñas", "desc": "Web moderna con precios claros, reseñas de alumnos, fotos de vehículos y equipo. Los jóvenes quieren transparencia de precios. Si no los muestras, se van a la competencia que sí los muestra."},
        ],
        "testimonial_quote": "Las matrículas han subido un 40% desde que empezamos con el marketing digital. TikTok nos ha dado una visibilidad que no imaginábamos.",
        "testimonial_author": "Director, Autoescuela, Barcelona",
        "cta_title": "¿Quieres más alumnos matriculados?",
        "cta_button": "Consulta gratis para autoescuelas",
        "faqs": [
            ("¿Cuánto cuesta el marketing para una autoescuela?", "Planes desde 350€/mes con SEO local y Google Business Profile. Con redes sociales y Google Ads desde 590€/mes. El coste de un alumno nuevo (matrícula + carnet) puede ser 800-1.500€, así que con 2-3 matrículas al mes la inversión se amortiza con creces."),
            ("¿Qué redes sociales usan los jóvenes para buscar autoescuela?", "TikTok e Instagram son las redes principales del público 18-25 años. TikTok para contenido viral y entretenido sobre el proceso de sacarse el carnet. Instagram para reels de alumnos aprobando, stories del día a día y reseñas. Google Maps es fundamental para la búsqueda local."),
            ("¿Funciona Google Ads para autoescuelas?", "Sí, especialmente para búsquedas de precio y cercanía. 'Autoescuela barata [zona]', 'precio carnet B [ciudad]' son búsquedas con alta intención. El CPC es bajo (1-3€) y la conversión a matrícula es directa. Ideal para campañas en septiembre y enero (picos de demanda)."),
        ],
    },

    "/marketing-para-talleres-de-coches/": {
        "title": "Marketing para Talleres de Coches | Más Clientes — Comunikoo",
        "meta_desc": "Marketing digital para talleres mecánicos: SEO local, Google Maps, reseñas y Google Ads. Capta clientes que buscan taller de confianza.",
        "h1": "Marketing para Talleres de Coches — Más Clientes que Confían en Tu Taller",
        "h1_short": "Marketing Talleres",
        "intro": "El conductor que necesita un taller busca en Google Maps, lee reseñas y elige el que le transmite más confianza. La confianza se construye online antes de que el cliente entre por la puerta.",
        "sector_name": "talleres de coches",
        "hook_stat": "El conductor busca taller en Google Maps, no en la guía.",
        "services": [
            {"title": "Google Business Profile", "desc": "Ficha completa con servicios, fotos del taller, horarios, zona de cobertura y reseñas. Aparece cuando buscan 'taller mecánico cerca de mí' o 'cambio de aceite [zona]'."},
            {"title": "Google Ads para Urgencias", "desc": "Campañas para búsquedas urgentes: 'grúa 24h', 'taller abierto sábado', 'ITV urgente [ciudad]'. Cuando el conductor tiene una urgencia, tu taller aparece primero."},
            {"title": "Reseñas y Confianza", "desc": "Sistema de solicitud de reseñas post-servicio. En talleres, la confianza lo es todo. Un taller con 50+ reseñas y 4.5 estrellas gana al que tiene 5 reseñas, aunque sea más barato."},
            {"title": "SMS/Email de Recordatorio", "desc": "Recordatorios de ITV, cambio de neumáticos por temporada, revisiones periódicas. Fideliza clientes y genera revisitas sin necesidad de publicidad constante."},
        ],
        "testimonial_quote": "Las reseñas en Google nos han cambiado el negocio. Pasamos de 15 a 87 reseñas en un año y los clientes nuevos mencionan que nos eligieron por las valoraciones.",
        "testimonial_author": "Propietario, Taller Mecánico, Barcelona",
        "cta_title": "¿Quieres más clientes en tu taller?",
        "cta_button": "Consulta gratis para talleres",
        "faqs": [
            ("¿Cuánto cuesta el marketing para un taller?", "Planes desde 290€/mes con Google Business Profile y gestión de reseñas. Con Google Ads para urgencias y servicios específicos desde 490€/mes. El coste medio de un servicio de taller (200-1.000€) hace que la inversión sea muy rentable."),
            ("¿Las reseñas influyen mucho en talleres?", "Muchísimo. El taller es un negocio de confianza: el cliente te deja su coche (un bien de alto valor). Las reseñas son la prueba social más potente. Un taller con muchas reseñas positivas se posiciona mejor en Google Maps y convierte más visitas en clientes."),
            ("¿Necesito web si estoy en Google Maps?", "Google Maps es fundamental pero una web aporta mucho: puedes mostrar servicios detallados, precios orientativos, galería del taller y posicionar para keywords que Google Maps no cubre (ej: 'especialista BMW [ciudad]'). La web + Google Maps es la combinación ganadora."),
        ],
    },

    "/marketing-para-gimnasios/": {
        "title": "Marketing para Gimnasios | Más Socios Todo el Año — Comunikoo",
        "meta_desc": "Marketing digital para gimnasios: SEO local, campañas de captación, redes sociales y retención. Más socios durante todo el año, no solo en enero.",
        "h1": "Marketing para Gimnasios — Más Socios Todo el Año, No Solo en Enero",
        "h1_short": "Marketing Gimnasios",
        "intro": "La mayoría de gimnasios viven del pico de enero y septiembre. El resto del año luchan por retener socios. Una estrategia de marketing digital bien planificada genera nuevas altas todo el año y reduce las bajas.",
        "sector_name": "gimnasios",
        "hook_stat": "El 50% de los nuevos socios de enero se dan de baja antes de marzo.",
        "services": [
            {"title": "SEO Local para Gimnasios", "desc": "Posicionamiento en 'gimnasio cerca de mí', 'gym [barrio]', 'crossfit [zona]', 'pilates [ciudad]'. SEO local para que aparezcas cuando buscan un gimnasio en tu zona."},
            {"title": "Campañas de Captación", "desc": "Google Ads + Facebook/Instagram Ads para campañas de matrícula. Campañas estacionales optimizadas: enero (propósitos), septiembre (vuelta a la rutina), mayo (operación bikini). Segmentación por edad, intereses y proximidad."},
            {"title": "Redes Sociales Fitness", "desc": "Contenido motivacional, transformaciones de socios (con permiso), clases en directo, retos fitness, presentación de monitores. Instagram y TikTok son perfectos para crear comunidad fitness."},
            {"title": "Retención Digital", "desc": "Email marketing de onboarding para nuevos socios (primeras 4 semanas críticas), campañas de reactivación para socios inactivos, referral program digital (socio trae socio con descuento). Reducir las bajas es tan importante como captar."},
            {"title": "Web con Tour Virtual y Booking", "desc": "Web con galería, tour virtual 360°, horarios de clases en tiempo real, booking online de clases y precios claros. La transparencia de precios convierte: el gimnasio que oculta precios pierde al 60% de visitantes web."},
        ],
        "testimonial_quote": "Las altas mensuales han subido de 30 a 85 y las bajas se han reducido un 25%. El programa de referral digital ha sido un éxito increíble.",
        "testimonial_author": "Director, Centro Deportivo, Madrid",
        "cta_title": "¿Quieres más socios en tu gimnasio?",
        "cta_button": "Plan de marketing fitness gratis",
        "faqs": [
            ("¿Cuánto cuesta el marketing para un gimnasio?", "Los planes empiezan desde 490€/mes (SEO local + redes sociales básicas) y desde 990€/mes con Google Ads y campañas de captación. El coste medio de una cuota mensual de gimnasio (30-60€) hace que con 10-15 nuevos socios al mes ya sea muy rentable."),
            ("¿Cómo reduzco las bajas de socios?", "Con un programa de retención digital: email de onboarding las primeras 4 semanas (la fase crítica), notificaciones de nuevas clases, retos y logros, campañas de reactivación para socios que llevan 2+ semanas sin venir, y encuestas de satisfacción automáticas. La tecnología ayuda a personalizar la comunicación."),
            ("¿Cuándo debo empezar las campañas de captación?", "2-3 semanas antes de cada pico. Las campañas de enero deben empezar en diciembre (con mensajes de 'nuevo año, nuevo tú'). Las de septiembre en agosto (vuelta a la rutina). Y las de mayo en abril (operación verano). Pero el marketing digital funciona todo el año: siempre hay gente buscando gimnasio."),
        ],
    },

    "/marketing-para-academias/": {
        "title": "Marketing para Academias | Captación de Alumnos — Comunikoo",
        "meta_desc": "Marketing digital para academias y centros de formación: SEO, Google Ads, redes sociales y web con matrícula online.",
        "h1": "Marketing para Academias — Captación de Alumnos con Estrategia Digital",
        "h1_short": "Marketing Academias",
        "intro": "La captación de alumnos se ha digitalizado por completo. El futuro alumno compara centros en Google, lee reseñas, visita webs y pide información online. Tu academia necesita una presencia digital que convenza.",
        "sector_name": "academias",
        "hook_stat": "El 85% de los alumnos investigan online antes de matricularse.",
        "services": [
            {"title": "Web con Catálogo y Matrícula Online", "desc": "Web profesional con catálogo de cursos, precios, horarios, perfil de profesores, sistema de matrícula online y testimonios de alumnos. Todo optimizado para convertir visitantes en matriculados."},
            {"title": "SEO por Tipo de Curso", "desc": "Posicionamiento para 'academia inglés [ciudad]', 'clases de [materia] [zona]', 'curso [especialidad] online'. Cada tipo de formación tiene sus keywords y su landing page."},
            {"title": "Google Ads Estacional", "desc": "Campañas sincronizadas con los picos de demanda: septiembre (inicio de curso), enero (propósitos), junio (recuperación). Segmentación por edad, nivel y proximidad."},
            {"title": "Redes Sociales Educativas", "desc": "Contenido que muestra la vida del centro: clases en acción, logros de alumnos, eventos, open days. Instagram para público joven, Facebook para padres, LinkedIn para formación profesional."},
        ],
        "testimonial_quote": "Las matrículas online han pasado de 5 a 35 al mes. El SEO nos trae alumnos todo el año, no solo en septiembre.",
        "testimonial_author": "Directora, Academia de Idiomas, Barcelona",
        "cta_title": "¿Quieres más matrículas?",
        "cta_button": "Consulta gratis para educación",
        "faqs": [
            ("¿Cuánto cuesta el marketing para una academia?", "Planes desde 390€/mes con SEO y web optimizada. Con Google Ads y redes sociales desde 690€/mes. El valor de cada alumno (matrícula + mensualidades durante meses o años) hace que la inversión en marketing sea muy rentable a medio plazo."),
            ("¿Funciona Google Ads para captar alumnos?", "Sí, muy bien. Las búsquedas de cursos y formación tienen alta intención de compra. 'Academia inglés B2 [ciudad]' o 'curso contabilidad online' son búsquedas de personas que quieren matricularse. El CPC es moderado (1-4€) y la conversión a solicitud de información es alta."),
            ("¿Qué red social es mejor para academias?", "Depende de tu público: Instagram para alumnos jóvenes, Facebook para padres de alumnos menores, LinkedIn para formación profesional y empresarial. TikTok está funcionando muy bien para academias de idiomas y formación creativa."),
        ],
    },

    "/marketing-para-ecommerce/": {
        "title": "Marketing para Ecommerce | Estrategia 360 — Comunikoo",
        "meta_desc": "Marketing digital para ecommerce: SEO + Ads + email + CRO. Estrategia integral para escalar tu tienda online. Aumentamos tus ventas.",
        "h1": "Marketing para Ecommerce — Estrategia 360 para Escalar Tu Tienda Online",
        "h1_short": "Marketing Ecommerce",
        "intro": "Tener una tienda online no es suficiente: solo el 3% de los ecommerce en España son rentables. La diferencia está en la estrategia: tráfico cualificado, conversión optimizada y retención inteligente.",
        "sector_name": "ecommerce",
        "hook_stat": "Solo el 3% de las tiendas online son rentables.",
        "services": [
            {"title": "SEO para Ecommerce", "desc": "Posicionamiento de categorías y fichas de producto en Google. Arquitectura web optimizada, contenido para categorías, blog estratégico y SEO técnico específico para tiendas online."},
            {"title": "Google Shopping y Performance Max", "desc": "Tus productos con foto y precio en los primeros resultados de Google. Optimización del feed de Merchant Center, campañas Shopping y Performance Max para maximizar ROAS."},
            {"title": "Meta Ads para Ecommerce", "desc": "Facebook e Instagram Ads con catálogo dinámico: retargeting de productos visitados, lookalike audiences, campañas de conversión y Advantage+ Shopping."},
            {"title": "Email Marketing y Automatización", "desc": "Flujos automatizados: bienvenida, carrito abandonado, post-compra, cross-sell, winback. El email genera un retorno de 42€ por cada 1€ invertido en ecommerce."},
            {"title": "CRO y Optimización de Conversión", "desc": "Test A/B en fichas de producto, checkout, homepage. Análisis de heatmaps y grabaciones de sesión. Reducción de abandono de carrito y mejora de tasa de conversión."},
            {"title": "Analítica y Atribución", "desc": "Configuración avanzada de GA4, enhanced ecommerce tracking, modelos de atribución multicanal. Saber exactamente qué canal genera cada venta para invertir mejor."},
        ],
        "testimonial_quote": "Pasamos de 150 a 800 pedidos mensuales en 10 meses. La combinación de SEO + Shopping + email ha sido la clave del crecimiento.",
        "testimonial_author": "Fundador, Tienda Online de Moda, Barcelona",
        "cta_title": "¿Quieres escalar tu ecommerce?",
        "cta_button": "Auditoría ecommerce gratuita",
        "faqs": [
            ("¿Cuánto debería invertir en marketing para mi ecommerce?", "Como regla general, entre el 10% y 20% de tu facturación objetivo. Para ecommerce en fase de lanzamiento (0-1.000 pedidos/mes), recomendamos mínimo 1.500€/mes en servicios + presupuesto publicitario. Para fase de crecimiento, desde 2.500€/mes. El retorno se mide en ROAS (retorno por euro invertido en publicidad)."),
            ("¿Qué canal funciona mejor para ecommerce?", "Depende de tu producto y margen. Google Shopping funciona excelente para productos con demanda existente (el cliente busca 'zapatillas running Nike'). Instagram/Facebook Ads funcionan mejor para descubrimiento y compras impulsivas (moda, decoración, belleza). El email marketing es el canal con mayor ROI para retención. La estrategia ideal combina los tres."),
            ("¿Trabajáis con Shopify y WooCommerce?", "Sí, somos expertos en ambas plataformas. Shopify es ideal para escalar rápido con menos complicaciones técnicas. WooCommerce ofrece más flexibilidad y personalización. También trabajamos con PrestaShop. La elección depende de tu catálogo, necesidades técnicas y presupuesto."),
        ],
    },

    "/marketing-para-empresas-b2b/": {
        "title": "Marketing B2B | Leads Cualificados — Comunikoo",
        "meta_desc": "Marketing digital para empresas B2B: LinkedIn, SEO, contenido de autoridad, ABM y generación de leads cualificados. Ciclo de venta largo, resultados reales.",
        "h1": "Marketing B2B — Generación de Leads Cualificados para Empresas",
        "h1_short": "Marketing B2B",
        "intro": "El marketing B2B es diferente: ciclos de venta de meses, múltiples decisores, tickets altos y relaciones a largo plazo. Las tácticas que funcionan en B2C no sirven aquí. Necesitas una estrategia que genere confianza, autoridad y leads cualificados.",
        "sector_name": "empresas B2B",
        "hook_stat": "El 67% del buyer journey B2B se completa online antes de contactar con ventas.",
        "services": [
            {"title": "LinkedIn Marketing y Ads", "desc": "LinkedIn es el canal B2B por excelencia. Estrategia orgánica (perfil de empresa, publicaciones, artículos) + LinkedIn Ads (Sponsored Content, InMail, Lead Gen Forms). Segmentación por cargo, sector, tamaño de empresa y ubicación."},
            {"title": "SEO B2B de Nicho", "desc": "Keywords de alto valor con intención comercial clara: '[solución] para empresas', 'software de [función]', 'proveedor de [servicio]'. Contenido de autoridad que posiciona y genera leads cualificados."},
            {"title": "Marketing de Contenidos B2B", "desc": "Whitepapers, casos de estudio, webinars, informes sectoriales. Contenido que demuestra expertise y genera leads cualificados a través de formularios de descarga. Cada pieza de contenido es un imán de leads."},
            {"title": "ABM (Account Based Marketing)", "desc": "Estrategia dirigida a cuentas objetivo específicas: identificamos las empresas que quieres como cliente, creamos contenido personalizado y lanzamos campañas segmentadas solo para esas empresas."},
            {"title": "Email Marketing B2B", "desc": "Lead nurturing automatizado: secuencias de email que educan al prospecto a lo largo del ciclo de compra (awareness → consideration → decision). Integración con CRM para tracking completo del funnel."},
        ],
        "testimonial_quote": "Nuestro pipeline de oportunidades se ha triplicado y el coste por SQL (Sales Qualified Lead) se ha reducido un 45%. El contenido de LinkedIn genera más leads que nuestro equipo comercial.",
        "testimonial_author": "Director de Marketing, Empresa SaaS B2B, Madrid",
        "cta_title": "¿Quieres leads B2B cualificados?",
        "cta_button": "Consulta B2B gratuita",
        "faqs": [
            ("¿El marketing digital funciona para B2B?", "Absolutamente. El 67% del proceso de decisión B2B se completa online antes de que el comprador contacte con ventas. Si no tienes presencia digital, no existes en las fases iniciales del proceso de compra. El marketing digital B2B genera pipeline cualificado de forma predecible y escalable."),
            ("¿LinkedIn Ads es mejor que Google Ads para B2B?", "Son complementarios. LinkedIn es superior para targeting preciso (puedes segmentar por cargo, empresa, sector) pero tiene CPCs altos (5-15€). Google Ads captura demanda existente (alguien que busca activamente tu solución) con CPCs más variados. La estrategia ideal usa ambos: LinkedIn para awareness y Google para captura de demanda."),
            ("¿Cuánto tarda en dar resultados el marketing B2B?", "Más que en B2C, porque los ciclos de venta son más largos (3-12 meses). Los primeros resultados en generación de leads suelen verse en 2-3 meses con ads y 4-6 meses con SEO. El pipeline completo (lead → oportunidad → cierre) puede tardar 6-12 meses. Pero una vez que el motor funciona, los resultados se acumulan exponencialmente."),
            ("¿Qué es ABM y funciona para mi empresa?", "ABM (Account Based Marketing) es una estrategia que invierte los enfoques tradicionales: en vez de atraer leads masivamente y filtrar, identificas las empresas que quieres como cliente y creas campañas personalizadas para ellas. Funciona especialmente bien cuando tienes un mercado objetivo pequeño (<500 empresas) con tickets altos (>10.000€/año)."),
        ],
    },
}
